username: YourUsername
password: YourPassword
yt_key: Y0urK3y
log: [info, error, plain, debug, error] #remove debug for less verbose output
prepend: https://www.youtube.com/watch?v= #url that is prepended for video id's in submitted links